#Jekyll Config

title: "ChaozMc :: YANG"
email: chaozmc@is-jo.org
description: YANG (Yet Another Nerdy Guy)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chaozmc.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author-name:   ChaozMc
author-avatar: max.jpg

instafeed: false

facebook:  https://facebook.com/markus.feiler # Add your Facebook handle
instagram: https://www.instagram.com/chaozmc # Add your Facebook handle
github: https://github.com/chaozmc


markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages


sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-feed
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jemoji