#Jekyll Config

title: "ChaozMc :: YANG"
author: ChaozMc
email: chaozmc@is-jo.org
description: > # this means to ignore newlines until "show_exerpts:"
  YANG (Yet Another Nerdy Guy)
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chaozmc.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
social_links:
    #twitter: jekyllrb
  github:  chaozmc
    #rss: rss
    # dribbble: jekyll
  facebook: markus.feiler
    # flickr:   jekyll
  instagram: chaozmc
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

remote_theme: songzivong/dark-minima

plugins:
- jekyll-feed
- jekyll-remote-theme
 - jekyll-seo-tag
 - jekyll-sitemap
 - jemoji